### ISSUE TITLE
EFI Testing.

### ISSUE THREAD

**Issue by NLTD2010** [quynkk1/E5570-Hackintosh#1]

**Comment by NLTD2010** [comment]
[OpenCore 0.7.6.zip](https://github.com/quynkk1/E5570-Hackintosh/files/7838526/OpenCore.0.7.6.zip)
here

**Comment by quynkk1** [comment]
I will test later.
Thank for your contribution :3

**Comment by NLTD2010** [comment]
# <a href="https://github.com/acidanthera/RTCMemoryFixup/releases">rtc memory fixup.kext</a>

**Comment by NLTD2010** [comment]
add rtc memory fixup.kext and turn on DisableRtcChecksum

**Comment by quynkk1** [comment]
I think SSDT-ACOS-ACSE.aml can be emulated for Windows 8, no need to use SSDT-XOSI.aml

**Comment by NLTD2010** [comment]
> I think SSDT-ACOS-ACSE.aml can be emulated for Windows 8, no need to use SSDT-XOSI.aml

hmmmm , ok

**Comment by quynkk1** [comment]
![image](https://user-images.githubusercontent.com/95995307/148761386-608fcbd0-9879-4cf4-a5be-604c622129cd.png)

You can check ACOS/ACSE here

> > I think SSDT-ACOS-ACSE.aml can be emulated for Windows 8, no need to use SSDT-XOSI.aml
> 
> hmmmm , ok

**Comment by NLTD2010** [comment]
> ![image](https://user-images.githubusercontent.com/95995307/148761386-608fcbd0-9879-4cf4-a5be-604c622129cd.png)
> 
> You can check ACOS/ACSE here
> 
> > > I think SSDT-ACOS-ACSE.aml can be emulated for Windows 8, no need to use SSDT-XOSI.aml
> > 
> > 
> > hmmmm , ok

ok

**Comment by quynkk1** [comment]
> > ![image](https://user-images.githubusercontent.com/95995307/148761386-608fcbd0-9879-4cf4-a5be-604c622129cd.png)
> > You can check ACOS/ACSE here
> > > > I think SSDT-ACOS-ACSE.aml can be emulated for Windows 8, no need to use SSDT-XOSI.aml
> > > 
> > > 
> > > hmmmm , ok
> 
> ok

bủn bủn lờ mảo

**Comment by NLTD2010** [comment]
add this kext to fix sd card reader : <a href="https://github.com/CLAY-BIOS/Lenovo-ThinkPad-T450s-Hackintosh-Big-Sur-OpenCore/files/5874870/Sinetek-rtsx.kext.zip">Sinetek-rtsx.kext.zip</a>
